name: CI

on:
  push:
    paths:
      - "ge/**"
      - "tests/**"
      - "examples/**"
      - ".github/workflows/**"
      - "setup.py"
      - "README.md"
  pull_request:
    paths:
      - "ge/**"
      - "tests/**"
      - "examples/**"
      - ".github/workflows/**"
      - "setup.py"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.7"
            tf-version: "1.15.5"
            use-legacy-keras: "0"
          - python-version: "3.10"
            tf-version: "2.10.0"
            use-legacy-keras: "0"
          - python-version: "3.10"
            tf-version: "2.15.0"
            use-legacy-keras: "0"
          - python-version: "3.11"
            tf-version: "2.15.0"
            use-legacy-keras: "0"
          - python-version: "3.10"
            tf-version: "2.20.0"
            use-legacy-keras: "1"
          - python-version: "3.11"
            tf-version: "2.20.0"
            use-legacy-keras: "1"
          - python-version: "3.12"
            tf-version: "2.20.0"
            use-legacy-keras: "0"
          - python-version: "3.13"
            tf-version: "2.20.0"
            use-legacy-keras: "0"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ "${{ matrix.tf-version }}" == "2.10.0" ]]; then
            python -m pip install -q "numpy<2"
          fi
          python -m pip install -q "tensorflow==${{ matrix.tf-version }}"
          if [[ "${{ matrix.tf-version }}" == 1.* ]]; then
            python -m pip install -q "protobuf==3.20.3"
          fi
          if [[ "${{ matrix.use-legacy-keras }}" == "1" ]]; then
            python -m pip install -q "tf-keras~=2.20"
          fi
          python -m pip install -e ".[test]"
          if [[ "${{ matrix.tf-version }}" == "2.10.0" ]]; then
            python -m pip install -q "numpy<2"
          fi

      - name: Test with pytest
        timeout-minutes: 180
        env:
          TF_USE_LEGACY_KERAS: ${{ matrix.use-legacy-keras }}
        run: |
          pytest --cov=ge --cov=examples --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: pytest
          name: py${{ matrix.python-version }}-tf${{ matrix.tf-version }}
